### NOTE: GH API has no session validation, will return ErrRecordNotFound if it doesn't exist

### GitHub App Login
GET http://localhost:8000/github/login HTTP/1.1

### GitHub App List Users
GET http://localhost:8000/github/list-users HTTP/1.1

### GitHub App List Sessions
GET http://localhost:8000/github/list-sessions HTTP/1.1

### Get your avatar
GET http://localhost:8000/github/avatar HTTP/1.1
Session: 53ffd8e7-2a9c-4006-8de7-f9de4093c5ec

### Logout from session
GET http://localhost:8000/github/logout HTTP/1.1
Session: 53ffd8e7-2a9c-4006-8de7-f9de4093c5ec