### GitHub App Login
GET http://localhost:8000/github/login HTTP/1.1

### GitHub App List Users
GET http://localhost:8000/github/list-users HTTP/1.1

### GitHub App List Sessions
GET http://localhost:8000/github/list-sessions HTTP/1.1

### Get your avatar
GET http://localhost:8000/github/avatar HTTP/1.1
Session: 9c071ff2-3190-46fe-b9f9-852f7e259331

### Logout from session
GET http://localhost:8000/github/logout HTTP/1.1
