### Add TODO Item
POST http://localhost:8000/todo/add HTTP/1.1
Authorization: gh_token
Session: 1a3f48fd-1ab5-41f4-b075-0b858d26cb07
content-type: application/json

{
    "item": {
        "title": "item 1",
        "description": "my first todo item"
    }
}

### List TODO Items
GET http://localhost:8000/todo/list HTTP/1.1
Authorization: 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
Session: 1a3f48fd-1ab5-41f4-b075-0b858d26cb07

### Delete TODO Items (with same titles)
DELETE http://localhost:8000/todo/delete/title/item%201 HTTP/1.1
Authorization: gh_token
Session: 1a3f48fd-1ab5-41f4-b075-0b858d26cb07
content-type: application/json

{
    "title": "item 1"
}

### Delete TODO Item using ID
DELETE http://localhost:8000/todo/delete/e48d80d1-04cd-4465-95e4-71e145d92f3d HTTP/1.1
Authorization: gh_token
Session: 1a3f48fd-1ab5-41f4-b075-0b858d26cb07
content-type: application/json

{
    "id": "e48d80d1-04cd-4465-95e4-71e145d92f3d"
}

### Mark TODO Item complete
POST http://localhost:8000/todo/mark HTTP/1.1
Authorization: gh_token
Session: 1a3f48fd-1ab5-41f4-b075-0b858d26cb07
content-type: application/json

{
    "id": "609e01ab-2228-44c7-b322-b2836e31d87a"
}